version: '3.7'

services:
  export-html:
    container_name: prerender
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    ports:
      - '2800:2800'
